Repository uniplaces/ember-cli-uniq, pull requests merged in 2018-09, with the labels that each got.

#226 [RFC][UN-13470] to-money: fixed display of left (and all) currencies
  addon/helpers/to-money.js
  addon/utils/to-money.js
  package-lock.json
  package.json
  tests/dummy/app/router.js
  tests/dummy/app/routes/application.js
  tests/dummy/app/templates/components/demo-page.hbs
  tests/dummy/app/templates/snippets/to-money-1.hbs
  tests/dummy/config/environment.js
  tests/integration/helpers/to-money-test.js
  tests/unit/helpers/to-money-test.js
  tests/unit/utils/to-money-test.js
Labels: v0.4.0

#245 [RFC][NI] Add readOnly property to checked property on radio-button
  addon/components/uni-radio-button.js
  tests/dummy/app/templates/components/demo-page.hbs
  tests/dummy/app/templates/snippets/uni-radio-button-1.hbs
  tests/dummy/app/templates/snippets/uni-radio-button-2.hbs
  tests/integration/components/uni-radio-button-test.js
Labels: breaking change, v0.4.0

#262 [RFC][UN-14262 & UN-13756] Remove uniq bower dependency and update ember to 2.18
  .bowerrc
  .ember-cli
  .eslintrc.js
  .gitignore
  .npmignore
  .travis.yml
  CONTRIBUTING.md
  addon/styles/addon.scss
  blueprints/ember-cli-uniq/index.js
  bower.json
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  package-lock.json
  package.json
  testem.js
  tests/.eslintrc.js
  tests/dummy/app/styles/app.scss
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/dummy/public/crossdomain.xml
  tests/helpers/resolver.js
  tests/helpers/start-app.js
  tests/test-helper.js
Labels: breaking change, v0.4.0

#268 [RFC][NI] Add Enumerable super-class
  addon/enums/availability-options-type.js
  addon/enums/country-codes-type.js
  addon/enums/currency-symbol-type.js
  addon/enums/enumerable.js
  addon/enums/input-type.js
  addon/enums/key-codes-type.js
  addon/enums/phone-number-validation-type.js
  addon/enums/photo-size-types.js
  addon/enums/uni-alert-type.js
Labels: v0.4.0

#270 [RFC][UN-13839] Swap inline-svg with svg-jar
  .eslintrc.js
  addon/templates/components/uni-alert.hbs
  addon/templates/components/uni-button.hbs
  addon/templates/components/uni-carrousel.hbs
  addon/templates/components/uni-checkbox.hbs
  addon/templates/components/uni-country.hbs
  addon/templates/components/uni-datepicker-input.hbs
  addon/templates/components/uni-datepicker-range.hbs
  addon/templates/components/uni-datepicker.hbs
  addon/templates/components/uni-dropdown.hbs
  addon/templates/components/uni-header.hbs
  addon/templates/components/uni-modal.hbs
  addon/templates/components/uni-selector-button.hbs
  addon/templates/components/uni-signup.hbs
  addon/templates/components/uni-stars.hbs
  addon/templates/components/uni-tooltip.hbs
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/app/templates/components/demo-page.hbs
  tests/dummy/app/templates/snippets/uni-dropdown-2.hbs
  tests/dummy/app/templates/snippets/uni-main-photo-picker-1.hbs
  tests/integration/components/uni-dropdown-test.js
Labels: breaking change, v0.4.0

#273 [RFC][UN-14279] Improve uni-select
  addon/components/uni-select.js
  addon/templates/components/uni-select.hbs
  tests/dummy/app/routes/application.js
  tests/dummy/app/templates/components/demo-page.hbs
  tests/dummy/app/templates/snippets/uni-select-3.hbs
  tests/integration/components/uni-select-test.js
Labels: breaking change
